---
kind: pipeline
name: Assistant CI/CD

steps:
  - name: Tests
    pull: always
    image: python:3.8-slim
    environment:
      XDG_CACHE_HOME: tmp/pip
    commands:
      - pip3 install poetry
      - poetry install
      - poetry run pytest

  - name: Build & deploy
    pull: always
    image: python:3.8-slim
    network_mode: host
    privileged: true
    environment:
      XDG_CACHE_HOME: tmp/pip
      ANSIBLE_HOST_KEY_CHECKING: False
      VAULT:
        from_secret: VAULT
      PRIVATE_KEY:
        from_secret: PRIVATE_KEY
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apt-get update -qq && apt-get install -yqq openssh-client
      - pip3 install ansible docker-py
      - echo "$VAULT" > /tmp/vault
      - echo "$PRIVATE_KEY" > /tmp/private_key
      - chmod 600 /tmp/private_key
      - ansible-playbook --private-key=/tmp/private_key --vault-password-file=/tmp/vault --inventory=ansible/hosts.ini ansible/playbook.yml -e build_id=$CI_BUILD_NUMBER
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
