version: "2.1"
services:
    app:
        image: "registry.b7w.me/b7w/energostat:{{ build_branch }}-{{ build_id }}"
        restart: always
        ports:
            - "8080:5000"
        logging:
            driver: json-file
            options:
                max-file: "4"
                max-size: "4m"
